sonar.projectKey=Ansible
sonar.projectName=Ansible
sonar.sources=.
sonar.host.url=https://sonarqube-sonarqube-sonarqube.apps.ocpv.citiuscloud.local
sonar.token=sqp_ff0be9d61a51972b64130dabe6b8db67679f6775
